### ISSUE TITLE
Small typos

### ISSUE THREAD

**Issue by mforchner** [matestack/matestack-website#1]
Hi there, looks like a great project! 

There's are some small typos in your website, e.g.

in section "GitHub sponsoring tiers"

> You use **matetsack** as a

and in the "newsletter" section:

> We o**c**asionally  will send you news about updates ...

and in the "services" section

> Turn**y**key

and in 

> Extenden**d** know how for sponsors

---

Apart of that also a very slick site, thumb's up!

**Comment by jonasjabari** [comment]
Hey @mforchner! thank you for pointing out the typos! Haven't recognized your issue here...
